# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253046

# Verify that an audit event is generated for any successful/unsuccessful
# use of the "unix_update" by performing the following command to check
# the file system rules in "/etc/audit/audit.rules":
#
#     $ sudo grep -w "unix_update" /etc/audit/audit.rules
#     -a always,exit -F path=/usr/sbin/unix_update -F perm=x -F auid>=1000 -F auid!=unset -k privileged
#
# If the command does not return a line, or the line is commented out,
# this is a finding.


- name: TOSS-04-031200 - Successful/unsuccessful uses of the "unix_update" in TOSS must generate an audit record.
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: -a always,exit -F path=/usr/sbin/unix_update -F perm=x -F auid>=1000 -F auid!=unset -k privileged
  notify: Build auditd rules
  when:
    - toss_04_031200 | bool
  tags:
    - V-253046
    - SRG-OS-000471-GPOS-00215
    - TOSS-04-031200
    - DISA-STIG-TOSS-04-031200
    - medium_severity
    - CCI-000172
