# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253049

# Verify that an audit event is generated for any successful/unsuccessful
# use of "userhelper" by performing the following command to check the
# file system rules in "/etc/audit/audit.rules":
#
#     $ sudo grep -w "userhelper" /etc/audit/audit.rules
#     -a always,exit -F path=/usr/sbin/userhelper -F perm=x -F auid>=1000 -F auid!=unset -k privileged
#
# If the command does not return a line, or the line is commented out,
# this is a finding.


- name: TOSS-04-031230 - Successful/unsuccessful uses of "userhelper" in TOSS must generate an audit record.
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: -a always,exit -F path=/usr/sbin/userhelper -F perm=x -F auid>=1000 -F auid!=unset -k privileged
  notify: Build auditd rules
  when:
    - toss_04_031230 | bool
  tags:
    - V-253049
    - SRG-OS-000471-GPOS-00215
    - TOSS-04-031230
    - DISA-STIG-TOSS-04-031230
    - medium_severity
    - CCI-000172
