# https://www.stigviewer.com/stig/tri-lab_operating_system_stack_toss_4/2022-08-29/finding/V-253038

# Verify if TOSS is configured to audit the execution of the "removexattr"
# system call, by running the following command:
#
#     $ sudo grep -w removexattr /etc/audit/audit.rules
#     -a always,exit -F arch=b32 -S removexattr -F auid>=1000 -F auid!=unset -k perm_mod
#     -a always,exit -F arch=b64 -S removexattr -F auid>=1000 -F auid!=unset -k perm_mod
#
#     -a always,exit -F arch=b32 -S removexattr -F auid=0 -k perm_mod
#     -a always,exit -F arch=b64 -S removexattr -F auid=0 -k perm_mod
#
# If the command does not return all lines, or the lines are commented out,
# this is a finding.


- name: TOSS-04-031120 - Successful/unsuccessful uses of the "removexattr" system call in TOSS must generate an audit record.
  block:
    - name: TOSS-04-031120 - Successful/unsuccessful uses of the "removexattr" system call in TOSS must generate an audit record, esp. arch=b32 and auid!=unset
      ansible.builtin.lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: -a always,exit -F arch=b32 -S removexattr -F auid>=1000 -F auid!=unset -k perm_mod
      notify: Build auditd rules
    - name: TOSS-04-031120 - Successful/unsuccessful uses of the "removexattr" system call in TOSS must generate an audit record, esp. arch=b64 and auid!=unset
      ansible.builtin.lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: -a always,exit -F arch=b64 -S removexattr -F auid>=1000 -F auid!=unset -k perm_mod
      notify: Build auditd rules
    - name: TOSS-04-031120 - Successful/unsuccessful uses of the "removexattr" system call in TOSS must generate an audit record, esp. arch=b32 and auid=0
      ansible.builtin.lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: -a always,exit -F arch=b32 -S removexattr -F auid=0 -k perm_mod
      notify: Build auditd rules
    - name: TOSS-04-031120 - Successful/unsuccessful uses of the "removexattr" system call in TOSS must generate an audit record, esp. arch=b64 and auid=0
      ansible.builtin.lineinfile:
        path: /etc/audit/rules.d/audit.rules
        line: -a always,exit -F arch=b64 -S removexattr -F auid=0 -k perm_mod
      notify: Build auditd rules
  when:
    - toss_04_031120 | bool
  tags:
    - V-253038
    - SRG-OS-000468-GPOS-00212
    - TOSS-04-031120
    - DISA-STIG-TOSS-04-031120
    - medium_severity
    - CCI-000172
