---

auditd_max_log_file: '320'
auditd_num_logs: '5'
auditd_max_log_file_action: 'rotate'
auditd_flush: 'incremental_async'
auditd_space_left: '100'
auditd_space_left_action: 'email'

login_banner_text: You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only.\n\nBy using this IS (which includes any device attached to this IS), you consent to the following conditions:\n\n-The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations.\n\n-At any time, the USG may inspect and seize data stored on this IS.\n\n-Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose.\n\n-This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy.\n\n-Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details.

inactivity_timeout_value: '900'
user_umask: '077'
pass_max_days: '60'
pass_min_days: '1'
pwquality_difok: '8'
pwquality_minlen: '15'
pwquality_retry: '3'
pwquality_ocredit: '-1'
pwhistory_remember: '24'
pam_faillock_deny: 3
pam_faillock_interval: 900
max_concurrent_login_sessions: 256
var_rekey_limit_size: 1G
var_rekey_limit_time: 1h
var_sudo_timestamp_timeout: '0'
var_tftpd_secure_directory: /var/lib/tftpboot
sshd_approved_ciphers: aes256-ctr,aes192-ctr,aes128-ctr
toss_end_of_support: {
  "4.3": "2022-5-1 01:00:00",
  "4.4": "2023-12-1 01:00:00",
  "4.5": "2023-5-1 01:00:00",
  "4.6": "2023-12-1 01:00:00",
  "4.7": "2024-5-1 01:00:00",
  "4.8": "2029-6-1 01:00:00"
}

controls:
  - toss_04_010000
  - toss_04_010010
  - toss_04_010020
  - toss_04_010030
  - toss_04_010040
  - toss_04_010050
  - toss_04_010060
  - toss_04_010070
  - toss_04_010080
  - toss_04_010090
  - toss_04_010100
  - toss_04_010110
  - toss_04_010120
  - toss_04_010140
  - toss_04_010150
  - toss_04_010160
  - toss_04_010170
  - toss_04_010180
  - toss_04_010210
  - toss_04_010220
  - toss_04_010230
  - toss_04_010240
  - toss_04_010250
  - toss_04_010280
  - toss_04_010330
  - toss_04_010340
  - toss_04_010350
  - toss_04_010360
  - toss_04_010370
  - toss_04_010380
  - toss_04_010390
  - toss_04_010400
  - toss_04_010410
  - toss_04_010420
  - toss_04_010430
  - toss_04_020000
  - toss_04_020010
  - toss_04_020020
  - toss_04_020030
  - toss_04_020050
  - toss_04_020060
  - toss_04_020070
  - toss_04_020120
  - toss_04_020140
  - toss_04_020150
  - toss_04_020160
  - toss_04_020170
  - toss_04_020180
  - toss_04_020190
  - toss_04_020200
  - toss_04_020210
  - toss_04_020230
  - toss_04_020240
  - toss_04_020250
  - toss_04_020260
  - toss_04_020270
  - toss_04_020280
  - toss_04_020290
  - toss_04_020300
  - toss_04_020310
  - toss_04_020320
  - toss_04_030000
  - toss_04_030010
  - toss_04_030060
  - toss_04_030080
  - toss_04_030090
  - toss_04_030120
  - toss_04_030130
  - toss_04_030140
  - toss_04_030150
  - toss_04_030160
  - toss_04_030170
  - toss_04_030180
  - toss_04_030190
  - toss_04_030310
  - toss_04_030320
  - toss_04_030330
  - toss_04_030340
  - toss_04_030350
  - toss_04_030360
  - toss_04_030370
  - toss_04_030380
  - toss_04_030390
  - toss_04_030400
  - toss_04_030410
  - toss_04_030420
  - toss_04_030430
  - toss_04_030440
  - toss_04_030450
  - toss_04_030460
  - toss_04_030470
  - toss_04_030480
  - toss_04_030490
  - toss_04_030500
  - toss_04_030510
  - toss_04_030520
  - toss_04_030540
  - toss_04_030550
  - toss_04_030560
  - toss_04_030570
  - toss_04_030580
  - toss_04_030590
  - toss_04_030600
  - toss_04_030610
  - toss_04_030620
  - toss_04_030630
  - toss_04_030640
  - toss_04_030650
  - toss_04_030660
  - toss_04_030670
  - toss_04_030680
  - toss_04_030750
  - toss_04_030780
  - toss_04_030790
  - toss_04_030800
  - toss_04_030810
  - toss_04_030820
  - toss_04_030840
  - toss_04_030850
  - toss_04_030860
  - toss_04_030890
  - toss_04_030900
  - toss_04_030910
  - toss_04_030990
  - toss_04_031000
  - toss_04_031100
  - toss_04_031110
  - toss_04_031120
  - toss_04_031130
  - toss_04_031140
  - toss_04_031150
  - toss_04_031160
  - toss_04_031170
  - toss_04_031180
  - toss_04_031190
  - toss_04_031200
  - toss_04_031210
  - toss_04_031220
  - toss_04_031230
  - toss_04_031240
  - toss_04_031340
  - toss_04_031350
  - toss_04_031360
  - toss_04_031370
  - toss_04_031380
  - toss_04_040010
  - toss_04_040020
  - toss_04_040030
  - toss_04_040040
  - toss_04_040050
  - toss_04_040060
  - toss_04_040070
  - toss_04_040080
  - toss_04_040090
  - toss_04_040100
  - toss_04_040110
  - toss_04_040120
  - toss_04_040130
  - toss_04_040140
  - toss_04_040150
  - toss_04_040160
  - toss_04_040170
  - toss_04_040180
  - toss_04_040190
  - toss_04_040200
  - toss_04_040210
  - toss_04_040220
  - toss_04_040230
  - toss_04_040250
  - toss_04_040260
  - toss_04_040270
  - toss_04_040280
  - toss_04_040290
  - toss_04_040310
  - toss_04_040330
  - toss_04_040340
  - toss_04_040350
  - toss_04_040370
  - toss_04_040390
  - toss_04_040420
  - toss_04_040440
  - toss_04_040480
  - toss_04_040490
  - toss_04_040500
  - toss_04_040510
  - toss_04_040540
  - toss_04_040550
  - toss_04_040560
  - toss_04_040570
  - toss_04_040580
  - toss_04_040590
  - toss_04_040600
  - toss_04_040610
  - toss_04_040630
  - toss_04_040640
  - toss_04_040650
  - toss_04_040660
  - toss_04_040670
  - toss_04_040680
  - toss_04_040690
  - toss_04_040700
  - toss_04_040710
  - toss_04_040720
  - toss_04_040730
  - toss_04_040740
  - toss_04_040750
  - toss_04_040760
  - toss_04_040770
  - toss_04_040780
  - toss_04_040790
  - toss_04_040800
  - toss_04_040810
  - toss_04_040820
  - toss_04_040830
  - toss_04_040840
  - toss_04_040850
  - toss_04_040860
  - toss_04_040870
  - toss_04_040880
  - toss_04_040890
  - toss_04_040900
  - toss_04_040910
  - toss_04_040920
  - toss_04_040930
  - toss_04_040940
  - toss_04_040950
  - toss_04_040960

# Booleans that control which controls are run
# Generate with:
# `for f in ../parser/output/*.yml roles/stig/tasks/TOSS*.yml; do echo $(basename $f .yml): true; done`
toss_04_010000: true
toss_04_010010: true
toss_04_010020: true
toss_04_010030: true
toss_04_010040: true
toss_04_010050: true
toss_04_010060: true
toss_04_010070: true
toss_04_010080: true
toss_04_010090: true
toss_04_010100: true
toss_04_010110: true
toss_04_010120: true
toss_04_010140: true
toss_04_010150: true
toss_04_010160: true
toss_04_010170: true
toss_04_010180: true
toss_04_010210: true
toss_04_010220: true
toss_04_010230: true
toss_04_010240: true
toss_04_010250: true
toss_04_010280: true
toss_04_010330: true
toss_04_010340: true
toss_04_010350: true
toss_04_010360: true
toss_04_010370: true
toss_04_010380: true
toss_04_010390: true
toss_04_010400: true
toss_04_010410: true
toss_04_010420: true
toss_04_010430: true
toss_04_020000: true
toss_04_020010: true
toss_04_020020: true
toss_04_020030: true
toss_04_020050: true
toss_04_020060: true
toss_04_020070: true
toss_04_020120: true
toss_04_020140: true
toss_04_020150: true
toss_04_020160: true
toss_04_020170: true
toss_04_020180: true
toss_04_020190: true
toss_04_020200: true
toss_04_020210: true
toss_04_020230: true
toss_04_020240: true
toss_04_020250: true
toss_04_020260: true
toss_04_020270: true
toss_04_020280: true
toss_04_020290: true
toss_04_020300: true
toss_04_020310: true
toss_04_020320: true
toss_04_030000: true
toss_04_030010: true
toss_04_030060: true
toss_04_030080: true
toss_04_030090: true
toss_04_030120: true
toss_04_030130: true
toss_04_030140: true
toss_04_030150: true
toss_04_030160: true
toss_04_030170: true
toss_04_030180: true
toss_04_030190: true
toss_04_030310: true
toss_04_030320: true
toss_04_030330: true
toss_04_030340: true
toss_04_030350: true
toss_04_030360: true
toss_04_030370: true
toss_04_030380: true
toss_04_030390: true
toss_04_030400: true
toss_04_030410: true
toss_04_030420: true
toss_04_030430: true
toss_04_030440: true
toss_04_030450: true
toss_04_030460: true
toss_04_030470: true
toss_04_030480: true
toss_04_030490: true
toss_04_030500: true
toss_04_030510: true
toss_04_030520: true
toss_04_030540: true
toss_04_030550: true
toss_04_030560: true
toss_04_030570: true
toss_04_030580: true
toss_04_030590: true
toss_04_030600: true
toss_04_030610: true
toss_04_030620: true
toss_04_030630: true
toss_04_030640: true
toss_04_030650: true
toss_04_030660: true
toss_04_030670: true
toss_04_030680: true
toss_04_030750: true
toss_04_030780: true
toss_04_030790: true
toss_04_030800: true
toss_04_030810: true
toss_04_030820: true
toss_04_030840: true
toss_04_030850: true
toss_04_030860: true
toss_04_030890: true
toss_04_030900: true
toss_04_030910: true
toss_04_030990: true
toss_04_031000: true
toss_04_031100: true
toss_04_031110: true
toss_04_031120: true
toss_04_031130: true
toss_04_031140: true
toss_04_031150: true
toss_04_031160: true
toss_04_031170: true
toss_04_031180: true
toss_04_031190: true
toss_04_031200: true
toss_04_031210: true
toss_04_031220: true
toss_04_031230: true
toss_04_031240: true
toss_04_031340: true
toss_04_031350: true
toss_04_031360: true
toss_04_031370: true
toss_04_031380: true
toss_04_040010: true
toss_04_040020: true
toss_04_040030: true
toss_04_040040: true
toss_04_040050: true
toss_04_040060: true
toss_04_040070: true
toss_04_040080: true
toss_04_040090: true
toss_04_040100: true
toss_04_040110: true
toss_04_040120: true
toss_04_040130: true
toss_04_040140: true
toss_04_040150: true
toss_04_040160: true
toss_04_040170: true
toss_04_040180: true
toss_04_040190: true
toss_04_040200: true
toss_04_040210: true
toss_04_040220: true
toss_04_040230: true
toss_04_040250: true
toss_04_040260: true
toss_04_040270: true
toss_04_040280: true
toss_04_040290: true
toss_04_040310: true
toss_04_040330: true
toss_04_040340: true
toss_04_040350: true
toss_04_040370: true
toss_04_040390: true
toss_04_040420: true
toss_04_040440: true
toss_04_040480: true
toss_04_040490: true
toss_04_040500: true
toss_04_040510: true
toss_04_040540: true
toss_04_040550: true
toss_04_040560: true
toss_04_040570: true
toss_04_040580: true
toss_04_040590: true
toss_04_040600: true
toss_04_040610: true
toss_04_040630: true
toss_04_040640: true
toss_04_040650: true
toss_04_040660: true
toss_04_040670: true
toss_04_040680: true
toss_04_040690: true
toss_04_040700: true
toss_04_040710: true
toss_04_040720: true
toss_04_040730: true
toss_04_040740: true
toss_04_040750: true
toss_04_040760: true
toss_04_040770: true
toss_04_040780: true
toss_04_040790: true
toss_04_040800: true
toss_04_040810: true
toss_04_040820: true
toss_04_040830: true
toss_04_040840: true
toss_04_040850: true
toss_04_040860: true
toss_04_040870: true
toss_04_040880: true
toss_04_040890: true
toss_04_040900: true
toss_04_040910: true
toss_04_040920: true
toss_04_040930: true
toss_04_040940: true
toss_04_040950: true
toss_04_040960: true
